[global]

# If false, makes your Streamlit script start as a module.
developmentMode = false

[logger]

# Level of logging: 'error', 'warning', 'info', 'debug'.
level = "info"

[client]

# Controls whether uncaught app exceptions are displayed in the browser.
showErrorDetails = true

[server]

# The address where the server will listen for client and browser connections.
address = "0.0.0.0"

# The port where the server will listen for client and browser connections.
port = 8501

# Enables support for Cross-Origin Request Sharing (CORS) protection, for added security.
enableCORS = false

# Enables support for Cross-Site Request Forgery (XSRF) protection, for added security.
enableXsrfProtection = false

# Max size, in megabytes, for files uploaded with the file_uploader.
maxUploadSize = 200

# Max size, in megabytes, of messages that can be sent via the WebSocket connection.
maxMessageSize = 200

# Enables support for websocket compression.
enableWebsocketCompression = false

# The base path for the URL where Streamlit should be reachable from.
baseUrlPath = ""